//Generated by https:/quicktype.is

        export interface PokemonsResponsive {
    count:    number;
    next:     string;
    previous: null;
    results:  Result[];
}

export interface Result {
    name: string;
    url:  string;
}
